baseURL = 'https://joebyjo.github.io/joeblogo/'
languageCode = 'en-us'
title = 'whois JoeByjo'
pagination.pagerSize = 7

[module]
  [[module.imports]]
    path = "github.com/joebyjo/wreck-it-ralph-hugo-theme"

[params]
  logo = "JoeByjo"
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[menu]
  [[menu.main]]
    name = "Projects & Engagements"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1